# Generated by Django 4.1.5 on 2023-02-06 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('text', models.TextField(max_length=1600)),
                ('time_create', models.DateField(auto_now_add=True)),
                ('post_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_posts.category')),
            ],
        ),
    ]
